version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Backend..."
      - npm start
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync MERNSTACK-ECOMMERCE-FLIPCART-BACKEND s3://nodebackendapp --delete
© 2021 GitHub, Inc.